Advanced actions hw
andromedakroos/AutomatedTesting pull request #5
Opened 2023-01-11 23:30 UTC by andromedakroos

2023-01-16 19:43 UTC, wildpioneer requested changes

2023-01-16 19:43 UTC, wildpioneer commented on src/test/java/tests/DownloadFileTest.java
> +        Assert.assertTrue(waitsService.isFileExist("C:\\Users\\andro\\downloads\\" + fileName));
У меня не существует такого пути к папке - а следовательно нужен другой вариант.
Файлы сохраняются в стандартную папку Downloads - а значит путь к ней можно найти

2023-01-22 14:13 UTC, andromedakroos commented on src/test/java/tests/DownloadFileTest.java
> +        Assert.assertTrue(waitsService.isFileExist("C:\\Users\\andro\\downloads\\" + fileName));
Да, точно, забыл про настройки драйвера, исправил

2023-01-22 14:14 UTC, andromedakroos commented on src/test/java/tests/DownloadFileTest.java
> +        Assert.assertTrue(waitsService.isFileExist("C:\\Users\\andro\\downloads\\" + fileName));
Спасибо!

2023-01-23 19:39 UTC, wildpioneer commented
Проверено

2023-01-23 19:39 UTC, closed without merging