Postman hw
andromedakroos/AutomatedTesting pull request #9
Opened 2023-02-12 22:36 UTC by andromedakroos

2023-02-15 22:18 UTC, wildpioneer requested changes

2023-02-15 22:18 UTC, wildpioneer commented on Test Rail Homework.postman_collection.json
> +					"raw": "{{base_url}}/index.php?/api/v2/delete_milestone/72",
Почему именно 72? Необходимо параметризировать

2023-02-15 22:18 UTC, wildpioneer commented on Test Rail Homework.postman_collection.json
> +	]
А где TestCases?

2023-02-18 12:50 UTC, andromedakroos commented on Test Rail Homework.postman_collection.json
> +					"raw": "{{base_url}}/index.php?/api/v2/delete_milestone/72",
Исправил

2023-02-18 12:51 UTC, andromedakroos commented on Test Rail Homework.postman_collection.json
> +	]
В задании написано CRUD только для Milestones

2023-02-28 11:56 UTC, wildpioneer commented
Проверено

2023-02-28 11:56 UTC, closed without merging